#!/usr/bin/env python3
"""sdlc skill CLI — create fcbtech/pm work items and drive Project #86 lifecycle fields.

All GitHub access goes through an authenticated `gh`. Pure logic lives in sdlc_core.
Field writes use two paths (validated):
  - org issue fields (Subtype/Priority/Release Stage/Story Points): setIssueFieldValue
  - project-scoped fields (Status/Review State/QA State): updateProjectV2ItemFieldValue
Run `sync-fields` once (and after any board schema change) to cache node-ids.
"""
import argparse
import datetime
import json
import os
import pathlib
import subprocess
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import sdlc_core  # noqa: E402

ORG = "fcbtech"
PM = os.environ.get("SDLC_PM_REPO", "fcbtech/pm")
PROJECT_NUMBER = 86
FIELD_IDS_PATH = pathlib.Path(__file__).parent.parent / "references" / "field-ids.md"


def gh(args, check=True):
    r = subprocess.run(["gh", *args], capture_output=True, text=True)
    if check and r.returncode != 0:
        sys.exit(f"gh {' '.join(args)} failed:\n{r.stderr}")
    return r.stdout


def gql(query, **variables):
    args = ["api", "graphql", "-f", f"query={query}"]
    for k, v in variables.items():
        args += ["-F", f"{k}={v}"] if isinstance(v, int) else ["-f", f"{k}={v}"]
    return json.loads(gh(args))


# ---------------------------------------------------------------- field ids

PROJECT_Q = """
query($org:String!,$num:Int!){
  organization(login:$org){
    projectV2(number:$num){
      id
      fields(first:50){ nodes{
        ... on ProjectV2FieldCommon{ id name dataType }
        ... on ProjectV2SingleSelectField{ options{ id name } }
      } }
    }
    issueFields(first:50){ nodes{
      ... on IssueFieldSingleSelect{ id name options{ id name } }
      ... on IssueFieldDate{ id name }
    } }
    issueTypes(first:20){ nodes{ id name } }
  }
}"""


def resolve_ids():
    d = gql(PROJECT_Q, org=ORG, num=PROJECT_NUMBER)["data"]["organization"]
    proj = d["projectV2"]
    out = {"project_id": proj["id"], "project_fields": {}, "org_fields": {}, "issue_types": {}}
    for f in proj["fields"]["nodes"]:
        if not f or "name" not in f:
            continue
        entry = {"id": f["id"], "dataType": f.get("dataType")}
        if f.get("options"):
            entry["options"] = {o["name"]: o["id"] for o in f["options"]}
        out["project_fields"][f["name"]] = entry
    for f in d["issueFields"]["nodes"]:
        if f and f.get("name"):
            entry = {"id": f["id"]}
            if f.get("options"):
                entry["options"] = {o["name"]: o["id"] for o in f["options"]}
            out["org_fields"][f["name"]] = entry
    for t in d["issueTypes"]["nodes"]:
        out["issue_types"][t["name"]] = t["id"]
    return out


def cmd_sync_fields(_a):
    ids = resolve_ids()
    FIELD_IDS_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIELD_IDS_PATH.write_text(
        "# Cached node-ids (generated by `sdlc_helper.py sync-fields`) — do not edit by hand\n\n"
        "```json\n" + json.dumps(ids, indent=2) + "\n```\n"
    )
    print(
        f"wrote {FIELD_IDS_PATH.name}: {len(ids['project_fields'])} project fields, "
        f"{len(ids['org_fields'])} org fields, {len(ids['issue_types'])} issue types"
    )


def load_ids():
    txt = FIELD_IDS_PATH.read_text()
    return json.loads(txt.split("```json", 1)[1].split("```", 1)[0])


# ---------------------------------------------------------------- field setters

ORG_FIELD_MUT = """
mutation($iss:ID!,$f:ID!,$o:ID!){
  setIssueFieldValue(input:{issueId:$iss, issueFields:[{fieldId:$f, singleSelectOptionId:$o}]}){clientMutationId}
}"""

PROJECT_FIELD_MUT = """
mutation($p:ID!,$i:ID!,$f:ID!,$o:String!){
  updateProjectV2ItemFieldValue(input:{projectId:$p,itemId:$i,fieldId:$f,value:{singleSelectOptionId:$o}}){projectV2Item{id}}
}"""

ORG_DATE_MUT = """
mutation($iss:ID!,$f:ID!,$d:String!){
  setIssueFieldValue(input:{issueId:$iss, issueFields:[{fieldId:$f, dateValue:$d}]}){clientMutationId}
}"""

ADD_ITEM_MUT = """
mutation($p:ID!,$c:ID!){ addProjectV2ItemById(input:{projectId:$p,contentId:$c}){item{id}} }"""


def org_field_mutation(issue_id, ids, field, option):
    f = ids["org_fields"][field]
    return ORG_FIELD_MUT, {"iss": issue_id, "f": f["id"], "o": f["options"][option]}


def project_field_mutation(item_id, ids, field, option):
    f = ids["project_fields"][field]
    return PROJECT_FIELD_MUT, {"p": ids["project_id"], "i": item_id, "f": f["id"], "o": f["options"][option]}


def set_org_field(issue_id, ids, field, option, dry=False):
    mut, v = org_field_mutation(issue_id, ids, field, option)
    if dry:
        print("DRY set_org_field", field, "=", option, v)
        return
    gql(mut, **v)


def set_project_field(item_id, ids, field, option, dry=False):
    mut, v = project_field_mutation(item_id, ids, field, option)
    if dry:
        print("DRY set_project_field", field, "=", option, v)
        return
    gql(mut, **v)


def add_to_board(issue_node_id, ids, dry=False):
    if dry:
        print("DRY add_to_board", issue_node_id)
        return None
    return gql(ADD_ITEM_MUT, p=ids["project_id"], c=issue_node_id)["data"]["addProjectV2ItemById"]["item"]["id"]


# ---------------------------------------------------------------- helpers

def _issue_node_id(num):
    return gh(["api", f"repos/{PM}/issues/{num}", "--jq", ".node_id"]).strip()


def _issue_db_id(num):
    return int(gh(["api", f"repos/{PM}/issues/{num}", "--jq", ".id"]).strip())


def _pm_item_id(num, ids):
    """Return (issue_node_id, project_item_id), adding the issue to the board if needed."""
    node = _issue_node_id(num)
    d = gql(
        "query($id:ID!){node(id:$id){... on Issue{projectItems(first:20){nodes{id project{number}}}}}}",
        id=node,
    )
    for it in d["data"]["node"]["projectItems"]["nodes"]:
        if it["project"]["number"] == PROJECT_NUMBER:
            return node, it["id"]
    return node, add_to_board(node, ids)


def _create_pm_issue(title, body, type_name, ids):
    url = gh(["issue", "create", "-R", PM, "--title", title, "--body", body or ""]).strip().splitlines()[-1]
    num = int(url.rsplit("/", 1)[-1])
    node = _issue_node_id(num)
    gql(
        "mutation($id:ID!,$t:ID!){updateIssue(input:{id:$id,issueTypeId:$t}){issue{number}}}",
        id=node, t=ids["issue_types"][type_name],
    )
    item = add_to_board(node, ids)
    return num, node, item


def _set_org_common(node, ids, *, subtype=None, priority=None, points=None):
    if subtype:
        set_org_field(node, ids, "Subtype", subtype)
    if priority:
        set_org_field(node, ids, "Priority", priority)
    if points:
        set_org_field(node, ids, "Story Points", str(points))


# ---------------------------------------------------------------- create ops

def cmd_create_task(a):
    ids = load_ids()
    role_map = json.loads(os.environ.get("SDLC_ROLES", '{"dev":[],"qa":[]}'))
    subtype = a.subtype or sdlc_core.resolve_subtype(a.assignee, role_map)
    if not subtype:
        sys.exit("Subtype unresolved: pass --subtype dev|qa (assignee not in SDLC_ROLES)")
    num, node, item = _create_pm_issue(a.title, a.body, "task", ids)
    if a.assignee:
        gh(["issue", "edit", str(num), "-R", PM, "--add-assignee", a.assignee])
    _set_org_common(node, ids, subtype=subtype, priority=a.priority, points=a.points)
    if a.epic:
        gh(["api", f"repos/{PM}/issues/{a.epic}/sub_issues", "-F", f"sub_issue_id={_issue_db_id(num)}"])
    print(f"created task {PM}#{num} subtype={subtype}"
          + (f" epic={a.epic}" if a.epic else ""))


def cmd_create_bug(a):
    ids = load_ids()
    num, node, item = _create_pm_issue(a.title, a.body, "bug", ids)
    _set_org_common(node, ids, subtype=a.subtype, priority=a.priority)
    if a.epic:
        gh(["api", f"repos/{PM}/issues/{a.epic}/sub_issues", "-F", f"sub_issue_id={_issue_db_id(num)}"])
    print(f"created bug {PM}#{num} subtype={a.subtype}")


def cmd_create_epic(a):
    ids = load_ids()
    num, node, item = _create_pm_issue(a.title, a.body, "epic", ids)
    _set_org_common(node, ids, priority=a.priority)
    if a.owner:
        gh(["issue", "edit", str(num), "-R", PM, "--add-assignee", a.owner])
    print(f"created epic {PM}#{num}")


# ---------------------------------------------------------------- dev flow

def cmd_start(a):
    ids = load_ids()
    node, item = _pm_item_id(a.pm, ids)
    set_project_field(item, ids, "Status", "WIP")
    today = datetime.date.today().isoformat()
    ds = ids["org_fields"].get("Dev Start")
    if ds:
        gql(ORG_DATE_MUT, iss=node, f=ds["id"], d=today)
        ds_msg = f", Dev Start={today}"
    else:
        ds_msg = " (Dev Start field not found — skipped)"
    me = gh(["api", "user", "--jq", ".login"]).strip()
    gh(["issue", "edit", str(a.pm), "-R", PM, "--add-assignee", me])
    print(f"started {PM}#{a.pm}: Status=WIP{ds_msg}, assignee={me}")


def cmd_open_pr(a):
    ids = load_ids()
    if not sdlc_core.has_investment_prefix(a.title):
        sys.exit("PR title must start with an investment prefix, e.g. 'feat: ...'")
    body = (a.body + "\n\n" if a.body else "") + f"Implements fcbtech/pm#{a.pm}\nhttps://github.com/{PM}/issues/{a.pm}"
    url = gh(["pr", "create", "-R", f"{ORG}/{a.repo}", "--base", a.base, "--head", a.head,
              "--draft", "--title", a.title, "--body", body]).strip().splitlines()[-1]
    gh(["issue", "comment", str(a.pm), "-R", PM, "--body", f"Implementation PR: {url}"])
    _node, item = _pm_item_id(a.pm, ids)
    set_project_field(item, ids, "Status", "WIP")
    set_project_field(item, ids, "Review State", sdlc_core.review_state_for_event("opened"))
    print(f"opened draft PR {url}; {PM}#{a.pm} Review State=Waiting for Review")


def cmd_ready(a):
    ids = load_ids()
    gh(["pr", "ready", str(a.pr), "-R", f"{ORG}/{a.repo}"])
    _node, item = _pm_item_id(a.pm, ids)
    set_project_field(item, ids, "Review State", sdlc_core.review_state_for_event("ready_for_review"))
    print(f"{a.repo}#{a.pr} ready; {PM}#{a.pm} Review State=In Review")


# ---------------------------------------------------------------- CLI

def build_parser():
    p = argparse.ArgumentParser(prog="sdlc")
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("sync-fields").set_defaults(func=cmd_sync_fields)

    t = sub.add_parser("create-task")
    t.set_defaults(func=cmd_create_task)
    t.add_argument("--title", required=True)
    t.add_argument("--body", default="")
    t.add_argument("--subtype", choices=["dev", "qa"])
    t.add_argument("--assignee")
    t.add_argument("--epic", type=int)
    t.add_argument("--priority", choices=["Urgent", "High", "Medium", "Low"])
    t.add_argument("--points", type=int, choices=[1, 2, 4, 8])

    b = sub.add_parser("create-bug")
    b.set_defaults(func=cmd_create_bug)
    b.add_argument("--title", required=True)
    b.add_argument("--body", default="")
    b.add_argument("--subtype", required=True, choices=["qa-bug", "production-bug", "suggestion"])
    b.add_argument("--epic", type=int)
    b.add_argument("--priority", choices=["Urgent", "High", "Medium", "Low"])

    e = sub.add_parser("create-epic")
    e.set_defaults(func=cmd_create_epic)
    e.add_argument("--title", required=True)
    e.add_argument("--body", default="")
    e.add_argument("--owner")
    e.add_argument("--priority", choices=["Urgent", "High", "Medium", "Low"])

    s = sub.add_parser("start")
    s.set_defaults(func=cmd_start)
    s.add_argument("pm", type=int)

    o = sub.add_parser("open-pr")
    o.set_defaults(func=cmd_open_pr)
    o.add_argument("pm", type=int)
    o.add_argument("--repo", required=True)
    o.add_argument("--head", required=True)
    o.add_argument("--base", required=True)
    o.add_argument("--title", required=True)
    o.add_argument("--body", default="")

    r = sub.add_parser("ready")
    r.set_defaults(func=cmd_ready)
    r.add_argument("pm", type=int)
    r.add_argument("--repo", required=True)
    r.add_argument("pr", type=int)

    return p


if __name__ == "__main__":
    args = build_parser().parse_args()
    args.func(args)
